services:
  dininghall1:
    build:
      context: .
      dockerfile: Dockerfile 
      args:
          configurations: configurations
          port: 8090
    ports:
      - "8090:8090"  
  dininghall2:
    build:
      context: .
      dockerfile: Dockerfile 
      args:
          configurations: configurations2
          port: 8091
    ports:
      - "8091:8091"
networks:
  default:
    name: restaurant
    external: true